[project]
name = "webknossos_utils_rafael"
version = "0.0.1"
authors = [
  { name="Rafael Camacho", email="rafael.camacho@gu.se" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
